#配置数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itheima_tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mysql@xiaofeng
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB




Mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true      # 开启驼峰命名



pagehelper:
  reasonable: true
  helper-dialect: mysql



logging:
  level:
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.jdbc: DEBUG



